src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    
    public function __toString(){
        // Or change the property that you want to show in the select.
        return $this->category_name;
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category_name;

    /**
     * @ORM\OneToMany(targetEntity=travaux::class, mappedBy="category")
     */
    private $Travaux;

    public function __construct()
    {
        $this->Travaux = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->category_name;
    }

    public function setCategoryName(string $category_name): self
    {
        $this->category_name = $category_name;

        return $this;
    }

    /**
     * @return Collection|travaux[]
     */
    public function getTravaux(): Collection
    {
        return $this->Travaux;
    }

    public function addTravaux(travaux $travaux): self
    {
        if (!$this->Travaux->contains($travaux)) {
            $this->Travaux[] = $travaux;
            $travaux->setCategory($this);
        }

        return $this;
    }

    public function removeTravaux(travaux $travaux): self
    {
        if ($this->Travaux->removeElement($travaux)) {
            // set the owning side to null (unless already changed)
            if ($travaux->getCategory() === $this) {
                $travaux->setCategory(null);
            }
        }

        return $this;
    }

}

src/Entity/Travaux.php
<?php

namespace App\Entity;

use App\Entity\Like;
use App\Entity\User;
use App\Entity\Category;

use App\Repository\TravauxRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TravauxRepository::class)
 */
class Travaux
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $travail;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lien_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lien_2;
    
    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="Travaux")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Date;

    /**
     * @ORM\Column(type="string", nullable=true, length=255)
     */
    private $Categorie;

    /**
     * @ORM\OneToMany(targetEntity=Like::class, mappedBy="Travaux")
     */
    private $likes;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $score;

    public function __construct()
    {
        $this->likes = new ArrayCollection();
   
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTravail(): ?string
    {
        return $this->travail;
    }

    public function setTravail(string $travail): self
    {
        $this->travail = $travail;

        return $this;
    }

    public function getLien1(): ?string
    {
        return $this->lien_1;
    }

    public function setLien1(string $lien_1): self
    {
        $this->lien_1 = $lien_1;

        return $this;
    }

    public function getLien2(): ?string
    {
        return $this->lien_2;
    }

    public function setLien2(?string $lien_2): self
    {
        $this->lien_2 = $lien_2;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->Date;
    }

    public function setDate(string $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->Categorie;
    }

    public function setCategorie(string $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setTravaux($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getTravaux() === $this) {
                $like->setTravaux(null);
            }
        }

        return $this;
    }

    /** 
     * Vérification si le travail est like par l'utilisateur
     * 
     * @param \App\Entity\User $user
     * @return boolean
    */

    public function isLikedByUser(User $user) : bool {

        foreach($this->likes as $like) {
            if ($like->getUser() === $user) return true;
        }

        return false;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(?int $score): self
    {
        $this->score = $score;

        return $this;
    }

}

src/Controller/TravauxController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\Persistence\ObjectManager;

use Doctrine\ORM\EntityManagerInterface;

use App\Repository\TravauxRepository;
use App\Repository\LikeRepository;
use App\Repository\UserRepository;

use Symfony\Component\HttpFoundation\Request;
use App\Service\FileUploader;
use App\Form\FileUploadType;
use App\Form\FileUploadType2;

use App\Entity\Travaux;
use App\Entity\Like;
use App\Entity\Category;

/**
* @Route("/travaux")
*/
class TravauxController extends AbstractController
{
    /**
     * @Route("/", name="app_travaux")
     */
    public function index(TravauxRepository $repo, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $category = $em->getRepository(Category::class)->findAll();
      
        
        if ($request->isMethod('POST')) {
        
          $travaux = $repo->rechercher($request->request->get('rechercher'));
        }
        
        else {
          $travaux = $repo->findBy(array(), array('score' => 'desc'));
          $travaux_top = $repo->findBy([],['score'=>'desc'],3);

        }

        return $this->render('travaux/index.html.twig', [
            'travaux' => $travaux,
            'category' => $category,
        ]);
    }

     /**
     * @Route("/podium", name="app_top")
     */
    public function podium(TravauxRepository $repo, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $category = $em->getRepository(Category::class)->findAll();
      
        
        if ($request->isMethod('POST')) {
        
          $travaux = $repo->rechercher($request->request->get('rechercher'));
        }
        
        else {
          $travaux_top = $repo->findBy([],['score'=>'desc'],3);
        }

        return $this->render('travaux/app_top.html.twig', [
            'travaux' => $travaux_top,
            'category' => $category,
        ]);
    }

   /**
     * @Route("/travaux_unique/{travaux}", name="travaux_unique")
     * @param Travaux $travaux
     *
     * @return Response
     */
    public function postunique(EntityManagerInterface $entityManager, Travaux $travaux)
    {
        $repository = $this->getDoctrine()->getRepository(Travaux::class);

        $travaux_unique = $repository->findOneBy(
            ['id' => $travaux],
        );
        return $this->render('travaux/unique_travaux.html.twig', [
            'travaux' => $travaux_unique,
            'id_user' => $travaux
        ]);
    }
    
    /**
     * @Route("/{id}/edit", name="app_edit_travail")
     * @param Travaux $travaux    
     * @return Response
     */
    public function edit(Request $request, EntityManagerInterface $entityManager, Travaux $travaux, $id): Response
    {

      $em = $this->getDoctrine()->getManager();
      $category = $em->getRepository(Category::class)->findAll();

      $form = $this->createForm(FileUploadType2::class, $travaux);
      $form->handleRequest($request);
      
      if ($form->isSubmitted() && $form->isValid()) 
      {
            $travaux = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($travaux);
            $em->flush();
       
            $this->addFlash('success', 'Travail bien modifié !');
            return $this->redirectToRoute('app_travaux', [
              'id' => $travaux->getId(),
              'category' => $category

              
          ]);      }
      return $this->render('travaux/edit_travaux.html.twig', [
        'form' => $form->createView(),
        
      ]);
    }

    
    /**
     * @Route("/{id}/delete", name="app_delete_travail")
     * @param Travaux $travaux    
     * @return Response
     */
    public function delete(Request $request, EntityManagerInterface $entityManager, Travaux $travaux, $id): Response
    {
      $em = $this->getDoctrine()->getManager();
      $entity = $em->getRepository(Travaux::class)->findOneBy(array('id' => $id));

      if ($entity != null){
          $em->remove($entity);
          $em->flush();
      }

      $this->addFlash('success', 'Enquête supprimé !');

      return $this->redirectToRoute('app_travaux');

    }


    

    /**
     * @Route("/new", name="app_upload")
     */
    public function excelCommunesAction(Request $request, FileUploader $file_uploader)
    {
      $form = $this->createForm(FileUploadType::class);
      $form->handleRequest($request);
      if ($form->isSubmitted() && $form->isValid()) 
      {
        $file = $form['upload_file']->getData();
        if ($file) 
        {
          $file_name = $file_uploader->upload($file);
          if (null !== $file_name) // for example
          {
            $directory = $file_uploader->getTargetDirectory();
            $full_path = $directory.'/'.$file_name;
            // Do what you want with the full path file...
            // Why not read the content or parse it !!!
            $uploads = new Travaux();
            $uploads->setTitre($form["Titre"]->getData());
            $uploads->setDescription($form["Description"]->getData()); // OK 
            $uploads->setTravail($file_name);
            $uploads->setLien1($form["Lien_1"]->getData());
            $uploads->setLien2($form["Lien_2"]->getData());
            $uploads->setUser($this->getUser());
            $uploads->setDate(date('d-m-Y'));
            $uploads->setCategorie($form["categorie"]->getData());
            $uploads->setScore(0);

            $em = $this->getDoctrine()->getManager();
            $em->persist($uploads);
            $em->flush();
    
          }
          else
          {
            return $this->redirectToRoute('app_travaux');

          }
        }
        $this->addFlash('success', 'Enquête ajouté !');

        return $this->redirectToRoute('app_travaux');
      }
      return $this->render('travaux/upload_travaux.twig', [
        'form' => $form->createView(),
      ]);
    }

    /**
     * Permet de liker ou unliker un travail
     * 
     * @Route("/{id}/like", name="app_like")
     * 
     * @param Travaux $travaux
     * @param EntityManagerInterface $manager
     * @param LikeRepository $likeRepo
     * @return Response 
     */
     public function like(Travaux $travaux, EntityManagerInterface $manager, LikeRepository $likeRepo): Response
     
     {

        $user = $this->getUser();


        if (!$user) return $this->json([
            'code' => 403,
            'message' => "Unauthorized"
        ], 403);

        if ($travaux->isLikedByUser($user)) {
          $travaux->setScore($travaux->getScore() - 1);
          $like = $likeRepo->findOneBy([
            'Travaux' => $travaux,
            'User' => $user
          ]);

          $manager->remove($like);
          $manager->flush();

          return $this->json([
            'code' => 200,
            'message' => "Like bien supprimé",
            'likes' => $likeRepo->count(['Travaux' => $travaux])
          ], 200);

        }

        $like = new Like(); 
        $travaux->setScore($travaux->getScore() + 1);
        $like->setTravaux($travaux)
             ->setUser($user);

        $manager->persist($like);
        $manager->flush();

        return $this->json([
          'code' => 200,
          'message' => "Like bien ajouté",
          'likes' => $likeRepo->count(['Travaux' => $travaux])
        ], 200);
   
        return $this->json(['code' => 200, 'message' => 'OK'], 200);
     }

     
}

templates/travaux/app_top.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ForumController!{% endblock %}

{% block body %}
<style>
.thread-post {
  padding: 10px;
  border-bottom: 1px solid #ddd;
  background-color: rgb(74, 85, 104, 0.66); /* For distinguishing every other post */;
  box-shadow: inset rgb(255 255 255 / 10%) 0px 1px 0px, rgb(0 0 0 / 12%) 0px 2px 2px, rgb(0 0 0 / 20%) 0px 4px 14px;

  border-top: 5px solid #046582;

}
.thread-post:nth-child(even) {
  background-color: #eee /* For distinguishing every other post */;
  background-color: rgb(80, 80, 100, 0.66); /* For distinguishing every other post */;
  box-shadow: inset rgb(255 255 255 / 10%) 0px 1px 0px, rgb(0 0 0 / 12%) 0px 2px 2px, rgb(0 0 0 / 20%) 0px 4px 14px;

}
body {
    background-color: #171e24!important;
    background-image: url('{{ asset('images/travail_bg.jpg') }}');
    color:white;
}
a {
    color: grey;
}
h1, h2 {width: 90vw; margin-right: auto; margin-left: auto; padding: 15px; font-size: 1.5em }


h1 {font-size: 2em!important; }
</style>

<div class="example-wrapper container-fluid" style="margin-top: 10vh; background-image:url('{{ asset('images/travail_bg.jpg') }}')">

    <h1 style="font-size: 250%; text-align:center;">Liste des travaux</h1>
    <form method="POST" style="background: none;">
    <p>
    <label class="floatLabel">Recherche :</label>
    <input type="text" name="rechercher" style="color:black;">
        <button type="submit" class="btn btn-primary">Rechercher !</button>

    </p>
    </form>
    <div class="row">

        <button class="btn btn-primary offset-lg-4 col-lg-2"><a href="{{ path('app_upload') }}">Ajouter un travail</a></button>
        <button class="btn btn-primary  col-lg-2"><a href="{{ path('app_travaux') }}">Afficher tous les travaux</a></button>

    </div> <!-- Fin du row -->
 
    {% for categorys in category %}
            
    <div class="category row" id="thread">    
    
    <hr class="center-star">
    <h2> {{ categorys.categoryName }}</h2>

        {% for travau in travaux %}

            {% if travau.categorie == categorys.categoryName %}
            
            
            <div class="col-4 thread-post" style="height: 650px; text-align: center;">
            <h3>{{travau.titre}}</h3> <br>
            <i class="fas fa-trophy"></i>


           
             {% set extension = travau.travail|split('.') %}

                {% if extension[1] == "mp4" or extension[1] == "avi" %} <!-- On vérifie que c'est un fichier vidéo qui est retourné -->

                <video controls style="width: 200px; height: 200px;">

                {% set url = travau.travail|split('.') %}

                <source src="{{ asset('uploads/' ~ travau.travail ~'') }}"
                            type="video/mp4">
                </video>

                {% endif %}

                {% if extension[1] == "png" or extension[1] == "gif" or extension[1] == "jpeg"  %} <!-- On vérifie que c'est un fichier image qui est retourné -->
      
                <div style="margin-left: auto; margin-right: auto; width: 200px; height: 200px; background-image:url('{{ asset('uploads/' ~ travau.travail ~'') }}'); background-position: center; background-size:cover; "></div>

                {% endif %}
                <p>publié le {{travau.date}} par {{travau.user.pseudo}}</p>
                
                <a href="{{ path('app_like', {'id': travau.id}) }}" class="btn btn-link js-like" style="background: white;">

                    {% if app.user and travau.isLikedByUser(app.user) %}
                        <i class="fas fa-thumbs-up"></i>
                    {% else %}
                        <i class="far fa-thumbs-up"></i>

                    {% endif %}

                    <span class="js-likes"> {{ travau.likes | length }} </span> 
                    <span class="js-label"> J'aime </span> <br>
                    
                </a>


                <div style="margin-right:auto; margin-left:auto,;">
                <button> <a href="{{ path('travaux_unique', {travaux: travau.id}) }}">En apprendre plus sur ce travail</a>
                </div>


                </div>

                {% endif %}

        {% endfor %}
    </div>
    {% endfor %}

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js
"></script>

<script>

    function onClickBtnLike(event){

        event.preventDefault();

        const url = this.href;
        const spanCount = this.querySelector('span.js-likes');
        const icone = this.querySelector('i');

        axios.get(url).then(function (response) {
            spanCount.textContent = response.data.likes;

            if (icone.classList.contains('fas')) {
                icone.classList.replace('fas', 'far');
            } else {
                icone.classList.replace('far', 'fas');
            }
        }).catch(function (error) {
            if (error.response.status === 403) {
                window.alert('Vous ne pouvez pas likez un article sans être connecté!')
            } else {
                window.alert('Une erreur s\'est produite, veuillez réessayer plus tard.')
            }
        })
    }

    document.querySelectorAll('a.js-like').forEach(function(link){
        link.addEventListener('click', onClickBtnLike)
    })
</script>

{% endblock %}

templates/travaux/edit_travaux.html.twig
{% extends 'base.html.twig' %}
{% block body %}
   {{ form_start(form, { attr: { 'accept-charset' : 'utf-8' }}) }}
  	<h2>Mettre à jour votre travail </h2>
		    <p>
          {{ form_label(form.Titre) }}
		      {{ form_label(form.Titre, 'Titre', {'label_attr': {'class': 'floatLabel'}}) }}

          {{ form_widget(form.Titre) }}
          {{ form_errors(form.Titre) }}
        </p>
		<p>
          {{ form_label(form.Description) }}
		  {{ form_label(form.Description, 'Description', {'label_attr': {'class': 'floatLabel'}}) }}

          {{ form_widget(form.Description) }}
          {{ form_errors(form.Description) }}
        </p>	
		<p>
          {{ form_label(form.Lien_1) }}
		  {{ form_label(form.Lien_1, 'Lien n°1', {'label_attr': {'class': 'floatLabel'}}) }}

          {{ form_widget(form.Lien_1) }}
          {{ form_errors(form.Lien_1) }}
        </p>
		    <p>
          {{ form_label(form.Lien_2) }}
		      {{ form_label(form.Lien_2, 'Lien n°2', {'label_attr': {'class': 'floatLabel'}}) }}

          {{ form_widget(form.Lien_2) }}
          {{ form_errors(form.Lien_2) }}
        </p>


        <p>
          {{ form_widget(form.send, {'label': "Modifier votre enquête"}) }}
        </p>
        {{ form_rest(form) }}
{{ form_end(form) }}
{% endblock %}

templates/travaux/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les travaux{% endblock %}

{% block body %}
<style>
.thread-post {
  padding: 10px;
  border-bottom: 1px solid #ddd;
  background-color: rgb(74, 85, 104, 0.66); /* For distinguishing every other post */;
  box-shadow: inset rgb(255 255 255 / 10%) 0px 1px 0px, rgb(0 0 0 / 12%) 0px 2px 2px, rgb(0 0 0 / 20%) 0px 4px 14px;

  border-top: 5px solid #046582;

}
.thread-post:nth-child(even) {
  background-color: #eee /* For distinguishing every other post */;
  background-color: rgb(80, 80, 100, 0.66); /* For distinguishing every other post */;
  box-shadow: inset rgb(255 255 255 / 10%) 0px 1px 0px, rgb(0 0 0 / 12%) 0px 2px 2px, rgb(0 0 0 / 20%) 0px 4px 14px;

}
body {
    background-color: #171e24!important;
    background-image: url('{{ asset('images/travail_bg.jpg') }}');
    color:white;
}
a {
    color: grey;
}
h1, h2 {width: 90vw; margin-right: auto; margin-left: auto; padding: 15px; font-size: 1.5em }


h1 {font-size: 2em!important; }
</style>

<div class="example-wrapper container-fluid" style="margin-top: 10vh; background-image:url('{{ asset('images/travail_bg.jpg') }}')">

    {% for message in app.flashes('success') %}
            <h1 class="alert alert-success">
                {{ message }}
            </h1>
        {% endfor %}
    <h1 style="font-size: 250%; text-align:center;">Liste des travaux</h1>
    <form method="POST" style="background: none;">
    <p>
    <label class="floatLabel">Recherche :</label>
    <input type="text" name="rechercher" style="color:black;">
        <button type="submit" class="btn btn-primary">Rechercher !</button>

    </p>
    </form>
    <div class="row">

        <button class="btn btn-primary offset-lg-5 col-lg-2"><a href="{{ path('app_upload') }}">Ajouter un travail</a></button>

    </div> <!-- Fin du row -->
 
    {% for categorys in category %}
            
    <div class="category row" id="thread">    
    
    <hr class="center-star">
    <h2> {{ categorys.categoryName }}</h2>

        {% for travau in travaux %}

            {% if travau.categorie == categorys.categoryName %}
            
            
            <div class="col-4 thread-post" style="height: 650px; text-align: center;">
            <h3>{{travau.titre}}</h3> <br>
           
             {% set extension = travau.travail|split('.') %}

                {% if extension[1] == "mp4" or extension[1] == "avi" %} <!-- On vérifie que c'est un fichier vidéo qui est retourné -->

                <video controls style="width: 200px; height: 200px;">

                {% set url = travau.travail|split('.') %}

                <source src="{{ asset('uploads/' ~ travau.travail ~'') }}"
                            type="video/mp4">
                </video>

                {% endif %}

                {% if extension[1] == "png" or extension[1] == "gif" or extension[1] == "jpeg"  %} <!-- On vérifie que c'est un fichier image qui est retourné -->
      
                <div style="margin-left: auto; margin-right: auto; width: 200px; height: 200px; background-image:url('{{ asset('uploads/' ~ travau.travail ~'') }}'); background-position: center; background-size:cover; "></div>

                {% endif %}
                <p>publié le {{travau.date}} par {{travau.user.pseudo}}</p>
                
                <a href="{{ path('app_like', {'id': travau.id}) }}" class="btn btn-link js-like" style="background: white;">

                    {% if app.user and travau.isLikedByUser(app.user) %}
                        <i class="fas fa-thumbs-up"></i>
                    {% else %}
                        <i class="far fa-thumbs-up"></i>

                    {% endif %}

                    <span class="js-likes"> {{ travau.likes | length }} </span> 
                    <span class="js-label"> J'aime </span> <br>
                    
                </a>


                <div style="margin-right:auto; margin-left:auto,;">
                <button> <a href="{{ path('travaux_unique', {travaux: travau.id}) }}">En apprendre plus sur ce travail</a>
                </div>


                </div>

                {% endif %}

        {% endfor %}
    </div>
    {% endfor %}

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js
"></script>

<script>

    function onClickBtnLike(event){

        event.preventDefault();

        const url = this.href;
        const spanCount = this.querySelector('span.js-likes');
        const icone = this.querySelector('i');

        axios.get(url).then(function (response) {
            spanCount.textContent = response.data.likes;

            if (icone.classList.contains('fas')) {
                icone.classList.replace('fas', 'far');
            } else {
                icone.classList.replace('far', 'fas');
            }
        }).catch(function (error) {
            if (error.response.status === 403) {
                window.alert('Vous ne pouvez pas likez un article sans être connecté!')
            } else {
                window.alert('Une erreur s\'est produite, veuillez réessayer plus tard.')
            }
        })
    }

    document.querySelectorAll('a.js-like').forEach(function(link){
        link.addEventListener('click', onClickBtnLike)
    })
</script>

{% endblock %}

templates/travaux/unique_travaux.html.twig
{% extends 'base.html.twig' %}

{% block title %}Travaux unique!{% endblock %}

{% block body %}
<style>
.thread-post {
  padding: 10px;
  padding-left: 35px;
  border-bottom: 1px solid #ddd;
  background-color: rgb(74, 85, 104, 0.66); /* For distinguishing every other post */;
  box-shadow: inset rgb(255 255 255 / 10%) 0px 1px 0px, rgb(0 0 0 / 12%) 0px 2px 2px, rgb(0 0 0 / 20%) 0px 4px 14px;
  width: 90%;
  border-top: 5px solid #046582;
  margin-right: auto;
}

body {
    background-color: #171e24!important;
    color:white;
    padding-left: 30px;
}
a {
    color: grey;
}
h1, h2 {width: 90vw; font-size: 1.5em; padding-bottom: 30px; }


h1 {font-size: 2em!important; }

</style>

<div class="thread-post container-fluid row" style="margin-top: 100px;">

<h2 class="col-12" style="font-size: 250%">Intitulé : {{travaux.titre}}</h2>
<p class="col-12" >Posté le {{ travaux.date }} par {{travaux.user.pseudo}}</p>
<div class="thread-left col-6" style="margin-top: 100px;">
 
     {% set extension = travaux.travail|split('.') %}

                {% if extension[1] == "mp4" or extension[1] == "avi" %} <!-- On vérifie que c'est un fichier vidéo qui est retourné -->

                <video controls style="width: 600px; height: 600px;">

                {% set url = travaux.travail|split('.') %}

                <source src="{{ asset('uploads/' ~ travaux.travail ~'') }}"
                            type="video/mp4">
                </video>

                {% endif %}

                {% if extension[1] == "png" or extension[1] == "gif" or extension[1] == "jpeg" or extension[1] == "jpg"  %} <!-- On vérifie que c'est un fichier image qui est retourné -->
      
                <img src="{{ asset('uploads/' ~ travaux.travail ~'') }}">

                {% endif %}
  
</div> <!-- fermeture div gauche -->

<div class="thread-right col-6" style="margin-top: 100px;">

    <span>Description : </br></br> {{ travaux.description|raw }}</span><br><br>
    <span>Lien n°1 : </br></br> <a target="_blank" href="{{ travaux.lien1 }}">{{ travaux.lien1 }}</a></span><br><br>
    <span>Lien n°2 : </br></br> <a target="_blank" href="{{ travaux.lien2 }}">{{ travaux.lien2 }}</a></span><br><br>

  {% if travaux.user.id == app.user.id %}
    <a href="{{path('app_edit_travail', {id: travaux.id})}}">Editer ce travail</a><br>
    <a href="{{path('app_delete_travail', {id: travaux.id})}}">Supprimer ce travail</a><br>


    {% endif %}

    <a href="{{path('app_travaux')}}">Retourner à la liste des travaux</a>

</div>

</div>
{% endblock %}